dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=story setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: T+eEbQJB7HY6CHxXghkREqoZXBgcvWWx7FK6KJTPfK3rFjJzjiHyTytuCFORTSqFpbuW9FrTdZFlSn0Zcs5i2GFZrp+ROq8F8czrdNTbPF753XvWBNKZ8HHU9PVufGN2+EjSFk6kOMWLHcsjskqQ3qsFvEFI1v5bSFBiw286vjl89hms/fqhdacQG0gy8Az8NgKCKA/D0a7nRY5su1TOP1G6KYTtFmL4sN4t5iBTnTFxn8xwWkl4kzzHAP1UhBLxG4sNsC+LNLN0l3JHu8kfsKbY8SHhZ8pqO8efBK6z1FV/x5EExpYAaWMyrnFjAlpgY1UZjxj0cp/lA9542zv/Ep1zySav5Ysk44LP6XfzjCnda7cCGZJCKuCn2c1DGXYDpSKcztAkEIqcRNGe+BRstOFwANGkImi7+ojLx4SEJR//r84EYvH27S7P2uTt8r5SO3YGKCosZV4eUvQEJGN+linHBfZG922YFKpP9UWpE6PYyLAgfKgnLu3h0EZ5W4UqL193VcU6jCKav6NIxoHiqcBhHRjd1fP/Up7bnhOF9B+37yycDTcLl3dzkGT5g1Qpp5P/lOLXi7wjiSCpnipfmYVAcStCBOJS9eguGEq6UaPw2uTHZXuRgxfEu1MrwIKGEn5wOTBuIKI7uXtAqLEG25bLnq1orCHwsOZDpe1InBU=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
